---
- name: Deploy RHEL monitoring
  hosts: all
  become: true

  # module_defaults:
  #  ansible.builtin.service:
  #   enabled: true
  #   state: started
  
  tasks:
  #  - name: Install cockpit package on RHEL
  
  #  - name: Copy cockpit.conf to /etc/cockpit/cockpit.conf

  #  - name: Start cockpit service

  #  - name: Wait 15 seconds port 9090
       
   

   