---
- name: Deploy RHEL monitoring
  hosts: all
  become: true

  module_defaults:
   ansible.builtin.service:
    enabled: true
    state: started
  
  tasks:
    - name: Install cockpit package on RHEL
      when: ansible_distribution == 'RedHat'
      ansible.builtin.package:
        name: cockpit
        state: present
  
    - name: Copy cockpit.conf to /etc/cockpit/cockpit.conf
      ansible.builtin.copy:
        src: cockpit.conf
        dest: /etc/cockpit/cockpit.conf
        owner: root
        group: root
        mode: 0644
        

    - name: Start cockpit service
      ansible.builtin.service:
        name: cockpit

    - name: Wait 15 seconds port 9090
      ansible.builtin.wait_for:
        port: 9090
        delay: 15
       
   

   